// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1alpha3

import (
	. "istio.io/client-go/pkg/apis/networking/v1alpha3"
)

// EnvoyFilterSlice represents a slice of *EnvoyFilter
type EnvoyFilterSlice []*EnvoyFilter
