// Code generated by skv2. DO NOT EDIT.

//go:generate mockgen -source ./sets.go -destination mocks/sets.go

package v1alpha2sets

import (
	access_smi_spec_io_v1alpha2 "github.com/servicemeshinterface/smi-sdk-go/pkg/apis/access/v1alpha2"

	sksets "github.com/solo-io/skv2/contrib/pkg/sets"
	"github.com/solo-io/skv2/pkg/ezkube"
	"k8s.io/apimachinery/pkg/util/sets"
)

type TrafficTargetSet interface {
	Keys() sets.String
	List() []*access_smi_spec_io_v1alpha2.TrafficTarget
	Map() map[string]*access_smi_spec_io_v1alpha2.TrafficTarget
	Insert(trafficTarget ...*access_smi_spec_io_v1alpha2.TrafficTarget)
	Equal(trafficTargetSet TrafficTargetSet) bool
	Has(trafficTarget *access_smi_spec_io_v1alpha2.TrafficTarget) bool
	Delete(trafficTarget *access_smi_spec_io_v1alpha2.TrafficTarget)
	Union(set TrafficTargetSet) TrafficTargetSet
	Difference(set TrafficTargetSet) TrafficTargetSet
	Intersection(set TrafficTargetSet) TrafficTargetSet
	Find(id ezkube.ResourceId) (*access_smi_spec_io_v1alpha2.TrafficTarget, error)
	Length() int
}

func makeGenericTrafficTargetSet(trafficTargetList []*access_smi_spec_io_v1alpha2.TrafficTarget) sksets.ResourceSet {
	var genericResources []ezkube.ResourceId
	for _, obj := range trafficTargetList {
		genericResources = append(genericResources, obj)
	}
	return sksets.NewResourceSet(genericResources...)
}

type trafficTargetSet struct {
	set sksets.ResourceSet
}

func NewTrafficTargetSet(trafficTargetList ...*access_smi_spec_io_v1alpha2.TrafficTarget) TrafficTargetSet {
	return &trafficTargetSet{set: makeGenericTrafficTargetSet(trafficTargetList)}
}

func NewTrafficTargetSetFromList(trafficTargetList *access_smi_spec_io_v1alpha2.TrafficTargetList) TrafficTargetSet {
	list := make([]*access_smi_spec_io_v1alpha2.TrafficTarget, 0, len(trafficTargetList.Items))
	for idx := range trafficTargetList.Items {
		list = append(list, &trafficTargetList.Items[idx])
	}
	return &trafficTargetSet{set: makeGenericTrafficTargetSet(list)}
}

func (s *trafficTargetSet) Keys() sets.String {
	return s.set.Keys()
}

func (s *trafficTargetSet) List() []*access_smi_spec_io_v1alpha2.TrafficTarget {
	var trafficTargetList []*access_smi_spec_io_v1alpha2.TrafficTarget
	for _, obj := range s.set.List() {
		trafficTargetList = append(trafficTargetList, obj.(*access_smi_spec_io_v1alpha2.TrafficTarget))
	}
	return trafficTargetList
}

func (s *trafficTargetSet) Map() map[string]*access_smi_spec_io_v1alpha2.TrafficTarget {
	newMap := map[string]*access_smi_spec_io_v1alpha2.TrafficTarget{}
	for k, v := range s.set.Map() {
		newMap[k] = v.(*access_smi_spec_io_v1alpha2.TrafficTarget)
	}
	return newMap
}

func (s *trafficTargetSet) Insert(
	trafficTargetList ...*access_smi_spec_io_v1alpha2.TrafficTarget,
) {
	for _, obj := range trafficTargetList {
		s.set.Insert(obj)
	}
}

func (s *trafficTargetSet) Has(trafficTarget *access_smi_spec_io_v1alpha2.TrafficTarget) bool {
	return s.set.Has(trafficTarget)
}

func (s *trafficTargetSet) Equal(
	trafficTargetSet TrafficTargetSet,
) bool {
	return s.set.Equal(makeGenericTrafficTargetSet(trafficTargetSet.List()))
}

func (s *trafficTargetSet) Delete(TrafficTarget *access_smi_spec_io_v1alpha2.TrafficTarget) {
	s.set.Delete(TrafficTarget)
}

func (s *trafficTargetSet) Union(set TrafficTargetSet) TrafficTargetSet {
	return NewTrafficTargetSet(append(s.List(), set.List()...)...)
}

func (s *trafficTargetSet) Difference(set TrafficTargetSet) TrafficTargetSet {
	newSet := s.set.Difference(makeGenericTrafficTargetSet(set.List()))
	return &trafficTargetSet{set: newSet}
}

func (s *trafficTargetSet) Intersection(set TrafficTargetSet) TrafficTargetSet {
	newSet := s.set.Intersection(makeGenericTrafficTargetSet(set.List()))
	var trafficTargetList []*access_smi_spec_io_v1alpha2.TrafficTarget
	for _, obj := range newSet.List() {
		trafficTargetList = append(trafficTargetList, obj.(*access_smi_spec_io_v1alpha2.TrafficTarget))
	}
	return NewTrafficTargetSet(trafficTargetList...)
}

func (s *trafficTargetSet) Find(id ezkube.ResourceId) (*access_smi_spec_io_v1alpha2.TrafficTarget, error) {
	obj, err := s.set.Find(&access_smi_spec_io_v1alpha2.TrafficTarget{}, id)
	if err != nil {
		return nil, err
	}

	return obj.(*access_smi_spec_io_v1alpha2.TrafficTarget), nil
}

func (s *trafficTargetSet) Length() int {
	return s.set.Length()
}
