// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1beta1

import (
	. "istio.io/client-go/pkg/apis/networking/v1beta1"
)

// DestinationRuleSlice represents a slice of *DestinationRule
type DestinationRuleSlice []*DestinationRule

// GatewaySlice represents a slice of *Gateway
type GatewaySlice []*Gateway

// ProxyConfigSlice represents a slice of *ProxyConfig
type ProxyConfigSlice []*ProxyConfig

// ServiceEntrySlice represents a slice of *ServiceEntry
type ServiceEntrySlice []*ServiceEntry

// WorkloadEntrySlice represents a slice of *WorkloadEntry
type WorkloadEntrySlice []*WorkloadEntry

// WorkloadGroupSlice represents a slice of *WorkloadGroup
type WorkloadGroupSlice []*WorkloadGroup

// VirtualServiceSlice represents a slice of *VirtualService
type VirtualServiceSlice []*VirtualService

// SidecarSlice represents a slice of *Sidecar
type SidecarSlice []*Sidecar
