// Code generated by skv2. DO NOT EDIT.

// Definitions for the Kubernetes types
package v1alpha1

import (
	. "istio.io/client-go/pkg/apis/extensions/v1alpha1"
)

// WasmPluginSlice represents a slice of *WasmPlugin
type WasmPluginSlice []*WasmPlugin
